#!/bin/sh
set -e

PKG="bedtools"
VER="2.16.2"
PKG_DIR=/usr/lib/${PKG}${VER}
TEST_EXE=bedToBam

if [ "$1" = "configure" ]; then
    if [ ! -e /usr/bin/${TEST_EXE} ]; then
        for pathname in ${PKG_DIR}/bin/*; do
            filename=`basename $pathname`
            update-alternatives --install /usr/bin/${filename} ${filename} /usr/bin/${filename}${VER} 1
        done
    fi
fi

